# Macro file for the visualization setting in the initialization phase 
# of the B1 example when running in interactive mode
#

# Use these open statements to open selected visualization
#
# Use this open statement to create an OpenGL view:
/vis/open OGL 600x600-0+0
#
# Use this open statement to create an OpenInventor view:
#/vis/open OI
#
# Use this open statement to create a .prim file suitable for
# viewing in DAWN:
#/vis/open DAWNFILE
#
# Use this open statement to create a .heprep file suitable for
# viewing in HepRApp:
#/vis/open HepRepFile
#
# Use this open statement to create a .wrl file suitable for
# viewing in a VRML viewer:
#/vis/open VRML2FILE
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume
#
# Specify view angle:
/vis/viewer/set/viewpointVector -1 0 0
/vis/viewer/set/lightsVector -1 0 0
#
# Specify style (surface, wireframe, auxiliary edges,...)
/vis/viewer/set/style wireframe
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 100
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2

/vis/viewer/set/lightsVector -0.2 0.5 -1
/vis/scene/add/trajectories
/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate

# To get nice view
# Make the "World" box invisible
/vis/geometry/set/visibility World 0 false

/vis/viewer/set/background white
/vis/viewer/set/style surface
/vis/viewer/set/hiddenMarker true
/vis/viewer/set/viewpointThetaPhi 120 150

/vis/modeling/trajectories/create/drawByParticleID
# blue:
/vis/modeling/trajectories/drawByParticleID-0/setRGBA mu+ 0 0 1 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA mu- 0 0 1 1
# red:
/vis/modeling/trajectories/drawByParticleID-0/setRGBA e- 1 0 0 1
# white:
/vis/modeling/trajectories/drawByParticleID-0/setRGBA e+ 1 1 1 1
# green:
/vis/modeling/trajectories/drawByParticleID-0/setRGBA gamma 0 1 0 1
# magenta:
/vis/modeling/trajectories/drawByParticleID-0/setRGBA opticalphoton 1 0 1 1
# cyan:
/vis/modeling/trajectories/drawByParticleID-0/setRGBA p+ 0 1 1 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA p- 0 1 1 1
# purple:
/vis/modeling/trajectories/drawByParticleID-0/setRGBA neutron 0.63 0.13 0.94 1
# yellow:
/vis/modeling/trajectories/drawByParticleID-0/setRGBA pi+ 1 1 0 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA pi- 1 1 0 1
# gold:
/vis/modeling/trajectories/drawByParticleID-0/setRGBA pi0 0.72 0.53 0.04 1
# darkred:
/vis/modeling/trajectories/drawByParticleID-0/setRGBA k+ 0.5 0 0 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA k- 0.5 0 0 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA kaon0L 0.5 0 0 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA kaon0S 0.5 0 0 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA kaon0 0.5 0 0 1

#
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush

# Gun Settings
/gun/particle proton
/gun/energy 7.00 MeV

/run/beamOn 1